### ISSUE TITLE
Repositório utilizado?

### ISSUE THREAD

**Issue by franzejr** [guru-ce/guru-heroku#1]
@Viniciuscarvalho @filipebarcos qual o objetivo desse repositório? Ele ainda está em vigor?

**Comment by filipebarcos** [comment]
não que eu saiba

On Wed, Dec 9, 2015 at 5:54 PM, Franzé Jr. <notifications@github.com> wrote:

> @Viniciuscarvalho <https://github.com/Viniciuscarvalho> @filipebarcos
> <https://github.com/filipebarcos> qual o objetivo desse repositório? Ele
> ainda está em vigor?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guru-ce/guru-heroku/issues/1>.
>



-- 
*Filipe Costa*
about.me/filipebarcos

**Comment by filipebarcos** [comment]
Acho que isso aqui era uma tentativa de um site sem  jekyll?

**Comment by franzejr** [comment]
Beleza. Vou deletar então
